name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-verison: 1.8
      - name: Grant executive permission for Gradle
        run: chmod +x gradlew
      - name: build
        run: ./gradlew clean build